Feature / business operations history resolver
codex-team/hawk.api.nodejs pull request #220
Opened 2020-08-06 13:44 UTC by neSpecc

2020-08-06 15:16 UTC, ilyamore88 commented on src/typeDefs/billing.ts
> +Transaction object
```suggestion
Business operation object
```

2020-08-13 10:31 UTC, nikmel2803 commented on src/resolvers/billingNew.ts
> +      return factories.usersFactory.findById(payload.userId.toHexString());
нужен даталодер

2020-08-13 10:31 UTC, nikmel2803 commented on src/resolvers/billingNew.ts
> +      return factories.workspacesFactory.findById(payload.workspaceId.toHexString());
и тут даталодер

2020-08-13 10:31 UTC, nikmel2803 commented on src/resolvers/billingNew.ts
> +      return factories.workspacesFactory.findById(payload.workspaceId.toHexString());
и туть

2020-09-01 16:54 UTC, neSpecc commented on src/resolvers/billingNew.ts
> +      return [
уберу этот мок, когда будут апрувы

2020-09-01 16:54 UTC, neSpecc commented on src/resolvers/billingNew.ts
> +      return [
он позволит потестить историю

2020-09-01 16:54 UTC, neSpecc commented on src/resolvers/billingNew.ts
> +      return factories.workspacesFactory.findById(payload.workspaceId.toHexString());
там внутри дата-лоадеры

2020-09-01 16:54 UTC, neSpecc commented on src/resolvers/billingNew.ts
> +      return factories.workspacesFactory.findById(payload.workspaceId.toHexString());
там внутри дата-лоадеры

2020-09-01 16:54 UTC, neSpecc commented on src/resolvers/billingNew.ts
> +      return factories.usersFactory.findById(payload.userId.toHexString());
там внутри дата-лоадеры

2020-09-02 16:54 UTC, gohabereg requested changes

2020-09-02 16:54 UTC, gohabereg commented on src/typeDefs/billing.ts
> +  amount: Int!
Тут может быть Float, или надо везде вести расчет в копейках (центах) и соответственно на клиенте уже делить на 100

2020-09-02 16:54 UTC, gohabereg commented on src/typeDefs/billing.ts
>    amount: Int!
Аналогично комменту выше

2020-09-02 16:54 UTC, gohabereg commented on src/typeDefs/billing.ts
> +type PayloadOfWorkspacePlanPurchase {
Для двух типов Payload вроде можно сделать интерфейс https://www.apollographql.com/docs/apollo-server/schema/unions-interfaces/#interface-type

Правда это, к сожалению, не уменьшает количество кода, а наоборот

2020-09-06 10:07 UTC, neSpecc commented on src/typeDefs/billing.ts
> +type PayloadOfWorkspacePlanPurchase {
тут так и сделано, только не через Interface type, а через Union Type, тк пэйлоады могут быть полностью разными, и они не имплементят какую-то структуру, а имеют свободную структуру.

2020-09-06 12:27 UTC, neSpecc commented on src/typeDefs/billing.ts
> +  amount: Int!
указал в описании, что тут всегда центы. Добавил конвертацию на клиенте

2020-09-06 12:27 UTC, neSpecc commented on src/typeDefs/billing.ts
>    amount: Int!
указал в описании, что тут всегда центы. Добавил конвертацию на клиенте

2020-09-07 12:56 UTC, gohabereg approved these changes

2020-09-07 13:00 UTC, nikmel2803 approved these changes

2020-09-07 14:10 UTC, merged