Update plans api
codex-team/hawk.api.nodejs pull request #228
Opened 2020-08-20 16:59 UTC by GeekaN2

Resolves codex-team/hawk.mono#16

2020-08-24 21:01 UTC, neSpecc commented on src/resolvers/workspace.js
> +      const transaction = await accounting.purchase({
тут не должна быть обработка ошибок?

2020-08-24 21:01 UTC, neSpecc commented on src/utils/telegram.ts
> +  await axios.post(botUrl, `message=${message}&parse_mode=HTMl`);
```suggestion
  await axios.post(botUrl, `message=${message}&parse_mode=HTML`);
```

2020-08-26 17:24 UTC, GeekaN2 commented on src/accounting/types/accountMutations.d.ts
> +   * Account igentifier: Which account should be purchased
Я с аккаунтинга копировал, надо будет и там описания поправить.

2020-08-27 10:04 UTC, neSpecc commented on src/resolvers/workspace.js
> +        throw new ApolloError('Something went wrong');
плохой текст ошибки

2020-08-27 10:04 UTC, neSpecc commented on src/resolvers/workspace.js
> +        throw new ApolloError('Something went wrong');
+ надо отправить лог в Хоука

2020-08-28 14:59 UTC, neSpecc requested changes

2020-08-28 14:59 UTC, neSpecc commented on src/accounting/types/transactions.d.ts
> +   * Transaction creation datetime
datetime это stirng, у тебя написано number. И надо уточнить единицы измерения — секунды или ms

2020-08-28 14:59 UTC, neSpecc commented on src/models/workspace.ts
> +    dtChange = Math.floor(dtChange / 1000);
все еще нужен коммент

2020-08-28 14:59 UTC, neSpecc commented on src/models/workspace.ts
> +   * Updating the date of the last charge
не написано, что за number возвращается

2020-08-28 14:59 UTC, neSpecc commented on src/models/workspace.ts
> +   * Push old plan to plan history. So that you can trace the history of changing plans
не написано, что за number возвращается

2020-08-28 14:59 UTC, neSpecc commented on src/resolvers/workspace.js
> +          description: 'Monthly charge',
это надо вынести в константу. 

```suggestion
          description: 'Monthly charge for the workspace plan',
```

2020-08-28 14:59 UTC, neSpecc commented on src/resolvers/workspace.js
> +          description: 'Monthly charge',
не думаете, что тут имеет смысл в описании указать, что это списание при смене плана?

@GeekaN2 @khaydarov @nikmel2803

2020-08-28 14:59 UTC, neSpecc commented on src/resolvers/workspace.js
> +      try {
мне не очень нравится идея оборачивать целиком всю логику в один try. А если списание сработало, но произошла ошибка далее?

2020-08-28 14:59 UTC, neSpecc commented on src/resolvers/workspace.js
> +      try {
но тут я не уверен.

2020-08-28 14:59 UTC, neSpecc commented on src/resolvers/workspace.js
> +      const message = `🤑 <b>${userModel.name || userModel.email}</b> changed plan of «<b>${workspaceModel.name}</b>» workspace
XSS

2020-08-28 18:38 UTC, GeekaN2 commented on src/resolvers/workspace.js
> +          description: 'Monthly charge',
А это даже не совсем ежемесячно списание, скорее просто списание за месяц при смене плана. Тогда не думаю, что есть смысл в константу выносить, ведь такое описание только здесь будет встречаться

2020-09-06 13:48 UTC, neSpecc commented on src/resolvers/workspace.js
> +        };
тут не хватает поля `dtCreated`, это обязательное поле. Возможно, его можно заполнять автоматически при инсерте? 

<img width="466" alt="image" src="https://user-images.githubusercontent.com/3684889/92327226-d1773a80-f060-11ea-9177-8b052b6bb4a6.png">

2020-09-15 10:37 UTC, neSpecc commented on src/resolvers/workspace.js
>            await workspaceModel.updateLastChargeDate(date);
а lastChardeDate нам не надо обновлять при переходе на бесплатный тариф?

2020-09-15 14:04 UTC, neSpecc commented on src/resolvers/workspace.js
> +            payload: payloadWorkspacePlanPurchase,
это можно вынести в какой-то метод?

2020-09-15 14:11 UTC, GeekaN2 commented on src/resolvers/workspace.js
> +            payload: payloadWorkspacePlanPurchase,
Если выносить, кажется, что только сложнее станет понимать. Можно сделать, но я конкретно здесь не стал бы.

2020-09-15 14:24 UTC, neSpecc approved these changes

2020-09-16 18:25 UTC, talyguryn approved these changes
к коду вопросов нет

2020-09-17 15:18 UTC, merged