Remove useless migrations
codex-team/hawk.api.nodejs pull request #247
Opened 2020-11-04 18:40 UTC by talyguryn

We no need this migrations cause all fixes already in code. They create problems with fresh installations.

2020-11-04 19:28 UTC, nikmel2803 approved these changes

2020-11-04 19:32 UTC, neSpecc requested changes

2020-11-04 19:32 UTC, neSpecc commented on migrations/20200224203115-add-index-to-users.js
> -/**
this migration can be helpful for future deployment

2020-11-18 18:25 UTC, neSpecc approved these changes

2020-11-18 18:43 UTC, merged