Add personal notifications
codex-team/hawk.api.nodejs pull request #251
Opened 2020-11-18 17:38 UTC by GeekaN2

2020-11-19 12:35 UTC, neSpecc requested changes

2020-11-19 12:35 UTC, neSpecc commented on src/resolvers/event.js
> +      rabbitmq.publish('', 'sender/email', JSON.stringify({
надо абстрагировать транспортный уровень и вынести название воркера в константу.

чтобы было что-то типа 

```ts
bgTasks.enqueue(WorkerType.EmailSender, {...})

```

2020-11-19 12:37 UTC, neSpecc requested changes

2020-11-19 12:37 UTC, neSpecc commented on src/resolvers/event.js
> +      rabbitmq.publish('', 'sender/email', JSON.stringify({
и еще надо упаковать это в модуль для пользовательских уведомлений.

2020-11-30 20:32 UTC, neSpecc commented on src/bgTasks.ts
> +export default {
почему не класс?

2020-11-30 20:32 UTC, neSpecc commented on src/personalNotifications.ts
> +export default {
зачем делать дефолтный экспорт, если все равно там объект? либо надо переделать на класс, либо просто экспрортировать функцию

2020-11-30 20:32 UTC, neSpecc commented on src/personalNotifications.ts
> +import bgTasks from './bgTasks';
почему этот файл прямо в корне лежит?

2020-12-02 06:34 UTC, neSpecc commented on src/utils/personalNotifications.ts
> +export default function sendNotifications(user: UserDBScheme, payload: string): void {
почему payload - string? может лучше делать json.stringify уже перед самой отправкой?

2020-12-02 06:34 UTC, neSpecc commented on src/utils/personalNotifications.ts
> +export default function sendNotifications(user: UserDBScheme, payload: string): void {
то есть внутри enqueue

2020-12-02 06:34 UTC, neSpecc commented on src/utils/personalNotifications.ts
> +export default function sendNotifications(user: UserDBScheme, payload: string): void {
имхо, можно оставить просто send, чтобы в коде было `notifications.send()`

2020-12-07 14:17 UTC, GeekaN2 commented on src/utils/personalNotifications.ts
> +export default function sendNotifications(user: UserDBScheme, payload: string): void {
Тогда я не смогу его типизировать, или будет any. Там же для каждого воркера свой payload

2020-12-07 14:34 UTC, neSpecc commented on src/utils/personalNotifications.ts
> +export default function sendNotifications(user: UserDBScheme, payload: string): void {
Ты сможешь его типизировать через [Discriminating Unions](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions)

2020-12-07 14:37 UTC, neSpecc commented on src/utils/personalNotifications.ts
> +export default function sendNotifications(user: UserDBScheme, payload: string): void {
Как то так будет

```
interface SenderWorkerTask<Payload>{
  type: string;
  payload: Payload;
}

interface PersonalNotifyPayload {
// ...
}

interface PersonalNotifyTask extends SenderWorkerTask<PersonalNotifyPayload> {
   type: 'personal-notification';
 }
```

2020-12-19 12:24 UTC, neSpecc requested changes

2020-12-19 12:24 UTC, neSpecc commented on src/types/bgTasks.ts
> +   * Use who assigned person to resolve an issue
```suggestion
   * Id of the user who has assigned a person to resolve the issue
```

2020-12-19 12:24 UTC, neSpecc commented on src/types/bgTasks.ts
> +export type AllPayloads = PersonalNotificationPayload
```suggestion
export type BgTaskPayload = PersonalNotificationPayload
```

2020-12-19 12:24 UTC, neSpecc commented on src/types/bgTasks.ts
> +export interface WorkerType {
непонятный интерфейс. Что за типы воркеров `excange` и `queue`? у нас нет таких воркеров. И где описание интерфейса и свойств?

2020-12-19 12:24 UTC, neSpecc commented on src/utils/personalNotifications.ts
> +export default function sendNotifications(user: UserDBScheme, payload: PersonalNotificationPayload): void {
почему во множественном числе? он же одно уведомление отправляет, просто в разные каналы

2021-01-12 09:10 UTC, neSpecc requested changes

2021-01-12 09:10 UTC, neSpecc commented on src/utils/personalNotifications.ts
> +      type: 'assignee',
почему тут захардкожен тип уведомления?

2021-01-12 15:11 UTC, ilyamore88 approved these changes

2021-01-12 18:06 UTC, neSpecc commented on src/utils/personalNotifications.ts
> +  if (task.type == 'assignee') {
лишняя проверка

2021-01-14 15:26 UTC, neSpecc approved these changes

2021-01-14 15:35 UTC, merged