Add context to express request
codex-team/hawk.api.nodejs pull request #273
Opened 2021-02-05 17:29 UTC by GeekaN2

Add context to express request so that it can be used in billing and not only

2021-02-05 17:42 UTC, neSpecc commented on src/index.ts
> +    this.app.use(async (req, res, next) => {
нужен коммент, зачем это

2021-02-05 18:16 UTC, nikmel2803 requested changes
Посмотри строку 113
Там у тебя снова создаётся контекст.
Получается, у тебя для запросов в graphql конктекст будет создаваться 2 раза
Надо сделать так, чтобы ApolloServer брал контекст от express

2021-02-08 14:39 UTC, nikmel2803 approved these changes

2021-02-08 14:45 UTC, khaydarov commented on src/billing/index.ts
> +  public createRoutes(app: express.Application): void {
наверное лучше назвать `createRoutesOnApp`. И комментарий в аннотации поправить

2021-02-08 14:45 UTC, khaydarov commented on src/index.ts
> +    this.app.use(async (req, res, next) => {
Add context on express request object so that to use its methods in any requests. Context is .... не хватает описания понятия "context".

2021-02-08 14:46 UTC, khaydarov commented on src/billing/index.ts
> +  public createRoutes(app: express.Application): void {
или appendRoutes

2021-02-08 18:08 UTC, neSpecc approved these changes

2021-02-08 18:11 UTC, khaydarov approved these changes

2021-02-08 18:12 UTC, merged