Billing: before payment endpoint
codex-team/hawk.api.nodejs pull request #274
Opened 2021-02-06 08:41 UTC by khaydarov

2021-02-07 18:59 UTC, neSpecc commented on src/billing/index.ts
> +    app.use(cors(this.corsOptionDelegate));
описать

2021-02-09 13:49 UTC, nikmel2803 requested changes

2021-02-09 13:49 UTC, nikmel2803 commented on src/billing/index.ts
> +  private corsOptionDelegate(req: express.Request, callback: Function): void {
а почему не юзать бы дефолтные настройки?
стоит ли хардкодить названия сайтов?

2021-02-09 13:49 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
> +     * @todo fetch workspace data: name, tariff and so on. I need services to work with storages
ты будешь доделывать это в этом реквесте или следующем?

2021-02-09 13:49 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
> +    const tariff = 'Basic';
может всё таки айдишник?

2021-02-09 14:56 UTC, khaydarov commented on src/billing/cloudpayments.ts
> +     * @todo fetch workspace data: name, tariff and so on. I need services to work with storages
в следующем

2021-02-09 14:56 UTC, khaydarov commented on src/billing/cloudpayments.ts
> +    const tariff = 'Basic';
в следующем сделаем

2021-02-09 15:12 UTC, nikmel2803 approved these changes

2021-02-09 16:14 UTC, nikmel2803 requested changes
Надо вместе с workspaceId принимать и id тарифного плана, за который пользователь хочет заплатить

2021-02-11 19:37 UTC, neSpecc approved these changes

2021-02-12 09:13 UTC, nikmel2803 approved these changes

2021-02-17 18:33 UTC, merged