Check billing route
codex-team/hawk.api.nodejs pull request #275
Opened 2021-02-09 13:07 UTC by GeekaN2

Logic in the check billing route

2021-02-09 13:39 UTC, nikmel2803 requested changes
давай сделаем лог в телегу обо всех ошибках (где у тебя возвращается не 0 и стоит catch)

2021-02-09 13:39 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
> +    if (body.Amount != plan.monthlyCharge) {
```suggestion
    if (body.Amount !== plan.monthlyCharge) {
```

2021-02-09 13:39 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
> +    const plan = await context.factories.plansFactory.findById(workspace.tariffPlanId.toString());
надо получать айди тарифного плана не от модели воркспейса (потому что мы будем менять тарифный план только в роуте pay)
Надо получать айди тарифного плана в Data, как и воркспейс

2021-02-09 13:39 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
> +    console.log(workspace);
лог надо убрать

2021-02-09 13:39 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
> +    telegram.sendMessage(`✅ User has passed all checks and wants to pay for the &laquo;${workspace.name}&raquo; workspace with ${plan.name} plan for <b>$${body.Amount}</b>`);
а этот лог в какой из чатов полетит? надо чтобы он был в отдельном чате

2021-02-13 12:58 UTC, nikmel2803 requested changes

2021-02-13 12:58 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
> +      HawkCatcher.send(new Error('There is no necessary data in the request'), body);
может стоит тут тоже отправить Data в контексте?

2021-02-13 12:58 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
> +      telegram.sendMessage(`❌Workspace was not found &laquo;${workspaceId}&raquo;`, TelegramBotURLs.Money);
Я думаю, стоит в каждый лог добавить `Billing / Check`, чтобы было понятно из какого именно роута это уведомление.
А ещё, возможно, не помешало бы добавить снизу дату и время отправки этого сообщения

2021-02-13 12:58 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
> +      telegram.sendMessage(`❌Workspace was not found &laquo;${workspaceId}&raquo;`, TelegramBotURLs.Money);
и в ошибки тоже добавить этот суффикс

2021-02-13 12:58 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
>      res.send({
Нужен лог о том, что всё прошло успешно

2021-02-13 13:04 UTC, nikmel2803 commented on src/utils/telegram.ts
>  module.exports = {
откуда тут module.exports?
К реквесту не относится, но пофикси плз

2021-02-15 09:52 UTC, nikmel2803 commented on test/integration/cases/billing/check.test.ts
> +  const mongoClient = new mongodb.MongoClient('mongodb://mongodb:27017', { useUnifiedTopology: true });
теперь это есть в глобальной переменной
посмотри как у меня сделано

2021-02-15 09:52 UTC, nikmel2803 commented on test/integration/cases/billing/check.test.ts
> +  test('Amount in request doesn\'t match with plan monthly charge', async () => {
А что делать то должен?
Не хватает should \ shouldn't

2021-02-15 10:01 UTC, neSpecc commented on test/integration/cases/billing/check.test.ts
> +     * Data to send to `check` webhook
не понятно, что не так с этим data. Надо описать, либо назвать соответствующим образом

2021-02-15 13:36 UTC, GeekaN2 commented on src/utils/telegram.ts
>  module.exports = {
В js файле используется, через export не работает там

2021-02-15 13:43 UTC, nikmel2803 commented on src/utils/telegram.ts
>  module.exports = {
хм, окей
вообще, в js из ts вроде экспортируется примерно так: `require('./telegram').default`
но можно сейчас и не заморачиваться

2021-02-15 13:59 UTC, GeekaN2 commented on src/billing/types/request.ts
> +  };
Для разных реквестов у нас скорее всего разные поля в Data будут

2021-02-15 14:01 UTC, GeekaN2 commented on src/billing/types/request.ts
> +  };
Его Виталик описывал, но тогда ещё не были известны все данные, которые нужны, так что там не актуальный интерфейс.

2021-02-15 17:23 UTC, neSpecc commented on src/billing/cloudpayments.ts
> +    try {
почему только этот await обернут в try? Разберись плз, как работают фабрики, может там уже внутри есть try?

2021-02-15 17:23 UTC, neSpecc commented on src/billing/types/request.ts
> +  };
я к тому, что не нужно перечислять поля в нескольких местах, а нужно использовать один и тот же тип

2021-02-15 17:23 UTC, neSpecc commented on src/billing/types/request.ts
> +  };
объясни конкретнее: для каких и что будет отличаться

2021-02-18 17:31 UTC, talyguryn requested changes

2021-02-18 17:31 UTC, talyguryn commented on .env.sample
> +TELEGRAM_MONEY_URL=
не нравятся мне такие названия переменных. не хватает слова CHAT или чего-то более ясного

2021-02-18 17:31 UTC, talyguryn commented on src/billing/cloudpayments.ts
> +      telegram.sendMessage(`❌[Billing / Check] There is no necessary data in the request`, TelegramBotURLs.Money);
может вынести эти два метода в одну общую конструкцию и метод? слишком много одинаковых строк кода

2021-02-18 17:31 UTC, talyguryn commented on test/integration/cases/billing/check.test.ts
> +const mainRequest = {
а какой тип у этого объекта? он где-то описан интерфейсом?

2021-02-18 17:32 UTC, GeekaN2 commented on test/integration/cases/billing/check.test.ts
> +const mainRequest = {
Да, тип CheckRequest

2021-02-18 17:34 UTC, talyguryn commented on test/integration/cases/billing/check.test.ts
> +const mainRequest = {
ок

2021-02-19 11:13 UTC, neSpecc commented on src/billing/types/request.ts
> +export interface PlanProlongationPayload {
этот тип надо взять из hawk.types

2021-02-19 11:16 UTC, GeekaN2 commented on src/billing/types/request.ts
> +export interface PlanProlongationPayload {
Его сейчас там нет, надо внести

2021-02-19 11:29 UTC, neSpecc commented on src/billing/types/request.ts
> +export interface PlanProlongationPayload {
внеси

2021-02-19 13:08 UTC, talyguryn approved these changes
вопросов не имею

2021-02-19 18:42 UTC, neSpecc approved these changes

2021-02-19 18:53 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
> +  private async getUser(userId: string, workspace: WorkspaceModel): Promise<ConfirmedMemberDBScheme> {
может getMember тогда уж?

2021-02-19 19:05 UTC, nikmel2803 approved these changes
👍

2021-02-19 19:10 UTC, merged