[Pay route] Add transactions to accounting
codex-team/hawk.api.nodejs pull request #282
Opened 2021-02-23 21:02 UTC by nikmel2803

2021-02-23 21:13 UTC, ilyamore88 requested changes

2021-02-23 21:13 UTC, ilyamore88 commented on src/billing/cloudpayments.ts
> +      }
Ты нигде не привязываешь новый аккаунт к воркспейсу

2021-02-23 21:13 UTC, ilyamore88 commented on test/integration/cases/billing/pay.test.ts
> +  name: 'WORKSPACE' + workspace.name,
```suggestion
  name: 'WORKSPACE:' + workspace.name,
```

2021-02-23 21:13 UTC, ilyamore88 commented on src/billing/cloudpayments.ts
> +        description: '',
Пустые описания для операций. Мне кажется, что стоит тут что-то передавать. Хотя бы ID операции в CP, чтобы можно было отслеживать.

2021-02-23 21:13 UTC, ilyamore88 commented on test/integration/accounting.env
> +REVENUE_ACCOUNT_ID=fcbae90d-508a-46c0-9bbf-1ee0d6e31987
Надеюсь, что ID не из прода 🗿

2021-02-23 21:14 UTC, nikmel2803 commented on test/integration/accounting.env
> +REVENUE_ACCOUNT_ID=fcbae90d-508a-46c0-9bbf-1ee0d6e31987
нет

2021-02-23 21:14 UTC, ilyamore88 commented on test/integration/accounting.env
> +REVENUE_ACCOUNT_ID=fcbae90d-508a-46c0-9bbf-1ee0d6e31987
👌

2021-02-23 21:38 UTC, ilyamore88 approved these changes

2021-02-24 05:40 UTC, neSpecc commented on src/billing/cloudpayments.ts
> +        description: `Purchasing for tariff plan with id ${tariffPlan._id}. CloudPayments transaction ID: ${body.TransactionId}`,
```suggestion
        description: `Charging for tariff plan with id ${tariffPlan._id}. CloudPayments transaction ID: ${body.TransactionId}`,
```

2021-02-24 05:40 UTC, neSpecc commented on test/integration/cases/billing/pay.test.ts
> +    expect(transactions.some(tr => tr.type === 'Purchase'));
тут не нужны тесты, что увеличился revenue и тд?

2021-02-24 05:40 UTC, neSpecc commented on src/billing/cloudpayments.ts
>      if (workspace && tariffPlan) {
когда будет рахардкожено todo про валидацию данных и обработку ошибок?

2021-02-24 05:40 UTC, neSpecc commented on src/billing/cloudpayments.ts
> +        accountId = (await context.accounting.createAccount({
у этого и последующих await нету обработки ошибок

2021-02-24 11:38 UTC, nikmel2803 commented on test/integration/cases/billing/pay.test.ts
> +    expect(transactions.some(tr => tr.type === 'Purchase'));
я думаю, такие тесты должны быть в самом аккаунтинге
считаю, что тут достаточно проверки на то, что создались нужные транзакции
а всю работу аккаунтинга тут тестить не хочется

2021-02-24 11:41 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
>      if (workspace && tariffPlan) {
в другом реквесте

2021-02-24 12:10 UTC, nikmel2803 commented on src/billing/cloudpayments.ts
> +        accountId = (await context.accounting.createAccount({
Я добавил, но полную обработку всё таки сделаю в отдельном реквесте вместе с тестами. Не хочу в этом.

2021-02-24 12:47 UTC, neSpecc approved these changes

2021-02-24 12:48 UTC, merged