Add a release for Event
codex-team/hawk.api.nodejs pull request #307
Opened 2021-04-25 13:32 UTC by GeekaN2

resolves https://github.com/codex-team/hawk.api.nodejs/issues/306

2021-05-07 09:24 UTC, neSpecc approved these changes

2021-05-17 06:52 UTC, nikmel2803 requested changes

2021-05-17 06:52 UTC, nikmel2803 commented on src/typeDefs/event.ts
> +  commitHash: String
может просто hash? и так понятно что коммита

2021-05-17 06:52 UTC, nikmel2803 commented on src/typeDefs/event.ts
> +  date: String
все эти поля необязательны? мне кажется нет, поэтому лучше пометить их как non-null

2021-05-17 06:52 UTC, nikmel2803 commented on src/typeDefs/event.ts
> +  id: String @renameFrom(name: "release")
```suggestion
  id: ID! @renameFrom(name: "release")
```

2021-05-17 06:52 UTC, nikmel2803 commented on src/typeDefs/event.ts
> +  commits: [Commit]
```suggestion
  commits: [Commit!]!
```

2021-05-17 06:52 UTC, nikmel2803 commented on src/typeDefs/event.ts
> +  projectId: String
непонятно зачем это

2021-05-17 06:54 UTC, GeekaN2 commented on src/typeDefs/event.ts
> +  id: String @renameFrom(name: "release")
Это строка, к примеру релиз может называться `Version 1.0` или `Salty Apple`

2021-05-17 06:56 UTC, nikmel2803 commented on src/typeDefs/event.ts
> +  id: String @renameFrom(name: "release")
всё равно же ID! подходит

2021-06-01 12:36 UTC, nikmel2803 reviewed
плюс некоторые комменты не пофикшены

2021-06-01 12:36 UTC, nikmel2803 commented on src/typeDefs/event.ts
> +  id: String @renameFrom(name: "release")
хотя я подумал, лучше назвать это не id а releaseName 🤔

2021-06-07 09:03 UTC, nikmel2803 approved these changes

2021-06-07 13:40 UTC, merged