[Feature] Generate invite hash
codex-team/hawk.api.nodejs pull request #326
Opened 2021-06-02 17:52 UTC by ilyamore88

Workspace factory generates invite hash and adds it to newly created workspace. Workspace query return inviteHash field.

2021-06-03 17:02 UTC, talyguryn approved these changes

2021-06-04 08:05 UTC, nikmel2803 commented on src/models/workspacesFactory.ts
> +  private static generateInviteHash(): string {
почему это метод фабрики? 🤔🤔
логичнее же в модель запихнуть и вызывать потом workspace.generateInviteHash()

2021-06-04 09:42 UTC, nikmel2803 commented on src/resolvers/workspace.js
> +      const workspace = await factories.workspacesFactory.findById(workspaceData._id);
кажется workspaceData уже должен быть моделью 🤔,поэтому искать его не надо

2021-06-04 13:07 UTC, nikmel2803 approved these changes

2021-06-04 13:21 UTC, neSpecc requested changes

2021-06-04 13:21 UTC, neSpecc commented on src/models/workspace.ts
> +    const randomNumber = Math.random();
это не серьезно, давай `crypto.randomBytes()`

2021-06-06 10:19 UTC, neSpecc approved these changes

2021-06-06 13:05 UTC, merged