[Feature] Join by invite hash
codex-team/hawk.api.nodejs pull request #337
Opened 2021-06-30 18:33 UTC by ilyamore88

Now api has two separates mutations:
- `joinByInviteLink` - for joining to a workspace by "public" invite link with invite hash. For example, `https://garage.hawk.so/join/my-invite-hash`;
- `confirmInvitation` - for joining to a workspace by "private" invite link from, for example, email message.

2021-07-01 05:14 UTC, nikmel2803 commented on src/resolvers/workspace.js
> +      return true;
по идее, должен возвращаться воркспейс с обновлённым полем team, а не просто true. Как обычно это принято делать: 
```
recordId: ID!
record: Workspace!
```

2021-07-01 05:14 UTC, nikmel2803 commented on src/resolvers/workspace.js
> +      return true;
лучше так сделать, если не запарно

2021-07-01 13:01 UTC, talyguryn approved these changes

2021-07-01 13:03 UTC, nikmel2803 approved these changes

2021-07-01 19:01 UTC, neSpecc requested changes

2021-07-01 19:01 UTC, neSpecc commented on src/typeDefs/workspace.ts
> +  Responce of updated workspace mutations
```suggestion
  Response of updated workspace mutations
```

2021-07-01 19:01 UTC, neSpecc commented on src/typeDefs/workspace.ts
> +  type UpdateWorkspacePayload {
мы вроде договорились называть такие объекты Response:
`UpdateWorkspaceResponse`

2021-07-02 13:49 UTC, neSpecc approved these changes

2021-07-03 10:17 UTC, merged